spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.6.129:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #添加时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 设置返回json的日期格式
  redis:
    host: 192.168.6.129
    port: 6379
    timeout: 10000
    maxIdle: 200
    maxTotal: 500
    maxWaitMillis: 1000
    testOnBorrow: true
  servlet:
    multipart:
      max-file-size: 300MB  #设置上传文件的大小设置
      max-request-size: 500MB
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: ahkakaxi@qq.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    auto-mapping-behavior: full # 开启自动映射
    map-underscore-to-camel-case: true # 下划线转驼峰
  type-aliases-package: issac.study.mbp.**.model #扫描表映射的类，默认是自动加下划线
  mapper-locations: classpath*:/issac/study/mbp/**/mapper/*.xml #classpath* 表示包括jar包内的类路径
  global-config:
    db-config:
      update-strategy: ignored  # 更新的时候，是否判断null或者empty，不判断
      insert-strategy: ignored  # 插入的时候，是否判断null或者empty，不判断
      select-strategy: ignored  # query查询的时候，是否判断null或者empty，不判断
my:
  config:
    my-enum: item1
