spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.99.3:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai #添加时区
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
  type-aliases-package: issac.study.mbp.**.model #扫描表映射的类，默认是自动加下划线
  mapper-locations: classpath*:issac.study.mbp.**.mapper #classpath* 表示包括jar包内的类路径
